name: ML Pipeline

on:
  push:
    paths:
      - 'data/raw_txt/**'
      - 'scripts/**'
      - 'src/**'
      - 'requirements.txt'
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # optional: weekly refresh

jobs:
  build-artifacts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          make all

      - name: Commit updated artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add artifacts/ data/raw/ data/processed/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update artifacts from CI"
            git push
          fi
